// client/src/components/ArticleList.vue
<script setup>
import { computed, ref, watchEffect, onMounted, onUnmounted } from 'vue'
import ArticleCard from './ArticleCard.vue'

const props = defineProps({
  articles: {
    type: Array,
    required: true
  }
})

const emit = defineEmits(['copy-summary'])

// Force re-computation trigger for storage changes
const storageVersion = ref(0)

// Watch for localStorage changes
function handleStorageChange() {
  storageVersion.value++
}

onMounted(() => {
  // Listen for storage changes (from useLocalStorage's deep watcher)
  window.addEventListener('local-storage-change', handleStorageChange)
})

onUnmounted(() => {
  window.removeEventListener('local-storage-change', handleStorageChange)
})

// Get live article state from localStorage for sorting
function getArticleState(article) {
  // Access storageVersion to make this reactive to storage changes
  storageVersion.value

  const storageKey = `newsletters:scrapes:${article.issueDate}`
  try {
    const raw = localStorage.getItem(storageKey)
    if (raw) {
      const payload = JSON.parse(raw)
      const liveArticle = payload.articles?.find(a => a.url === article.url)
      if (liveArticle) {
        // Use live state from localStorage
        if (liveArticle.removed) return 3  // Removed articles last
        if (liveArticle.tldrHidden) return 2  // TLDR hidden articles second to last
        if (liveArticle.read?.isRead) return 1  // Read articles middle
        return 0  // Unread articles first
      }
    }
  } catch (err) {
    console.error('Failed to read from localStorage:', err)
  }

  // Fallback to prop values if storage not available
  if (article.removed) return 3
  if (article.tldrHidden) return 2
  if (article.read?.isRead) return 1
  return 0
}

// Sort articles by state, then by original order
const sortedArticles = computed(() => {
  return [...props.articles].sort((a, b) => {
    const stateDiff = getArticleState(a) - getArticleState(b)
    if (stateDiff !== 0) return stateDiff

    // Within same state, preserve original order
    const orderA = a.originalOrder ?? 0
    const orderB = b.originalOrder ?? 0
    return orderA - orderB
  })
})

// Build sections with their articles
const sectionsWithArticles = computed(() => {
  const sections = []
  let currentSection = null

  sortedArticles.value.forEach((article, index) => {
    const sectionTitle = article.section
    const sectionEmoji = article.sectionEmoji
    const sectionKey = sectionTitle ? `${sectionEmoji || ''} ${sectionTitle}`.trim() : null

    // Check if we need a new section
    if (sectionKey && sectionKey !== currentSection) {
      sections.push({
        type: 'section',
        key: sectionKey,
        label: sectionKey
      })
      currentSection = sectionKey
    } else if (!sectionTitle && currentSection !== null) {
      // Reset section when we encounter an article without one
      currentSection = null
    }

    // Add the article
    sections.push({
      type: 'article',
      key: article.url,
      article: article,
      index: index
    })
  })

  return sections
})

// Track which sections have state changes for boundary markers
const articlesWithBoundaries = computed(() => {
  let lastState = -1
  return sortedArticles.value.map(article => {
    const currentState = getArticleState(article)
    const isFirstInCategory = currentState !== lastState && lastState !== -1
    lastState = currentState

    return {
      ...article,
      isFirstInCategory
    }
  })
})

function handleCopySummary() {
  emit('copy-summary')
}
</script>

<template>
  <div class="article-list">
    <template v-for="item in sectionsWithArticles" :key="item.key">
      <!-- Section title -->
      <div v-if="item.type === 'section'" class="section-title">
        {{ item.label }}
      </div>

      <!-- Article card -->
      <ArticleCard
        v-else
        :article="item.article"
        :index="item.index"
        :class="{ 'category-first': item.article.isFirstInCategory }"
        @copy-summary="handleCopySummary"
      />
    </template>
  </div>
</template>

<style scoped>
.article-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
  margin: 20px 0;
  padding: 0;
  list-style: none;
}

.section-title {
  margin: 18px 0 6px;
  text-align: center;
  font-style: italic;
  color: #9ca3af;
  font-size: 0.92em;
  letter-spacing: 0.01em;
}

/* Category boundaries - first item in a new category */
:deep(.article-card.category-first) {
  border-top: 3px solid var(--link, #1a73e8);
  padding-top: 16px;
  margin-top: 12px;
}
</style>

// client/src/components/ArticleList.jsx
import { useMemo, useState, useEffect } from 'react'
import ArticleCard from './ArticleCard'
import './ArticleList.css'

function ArticleList({ articles, onCopySummary }) {
  const [storageVersion, setStorageVersion] = useState(0)

  useEffect(() => {
    const handleStorageChange = () => {
      setStorageVersion(v => v + 1)
    }

    window.addEventListener('local-storage-change', handleStorageChange)
    return () => window.removeEventListener('local-storage-change', handleStorageChange)
  }, [])

  const getArticleState = (article) => {
    const storageKey = `newsletters:scrapes:${article.issueDate}`
    try {
      const raw = localStorage.getItem(storageKey)
      if (raw) {
        const payload = JSON.parse(raw)
        const liveArticle = payload.articles?.find(a => a.url === article.url)
        if (liveArticle) {
          if (liveArticle.removed) return 3
          if (liveArticle.tldrHidden) return 2
          if (liveArticle.read?.isRead) return 1
          return 0
        }
      }
    } catch (err) {
      console.error('Failed to read from localStorage:', err)
    }

    if (article.removed) return 3
    if (article.tldrHidden) return 2
    if (article.read?.isRead) return 1
    return 0
  }

  const sortedArticles = useMemo(() => {
    storageVersion
    return [...articles].sort((a, b) => {
      const stateDiff = getArticleState(a) - getArticleState(b)
      if (stateDiff !== 0) return stateDiff

      const orderA = a.originalOrder ?? 0
      const orderB = b.originalOrder ?? 0
      return orderA - orderB
    })
  }, [articles, storageVersion])

  const sectionsWithArticles = useMemo(() => {
    const sections = []
    let currentSection = null

    sortedArticles.forEach((article, index) => {
      const sectionTitle = article.section
      const sectionEmoji = article.sectionEmoji
      const sectionKey = sectionTitle ? `${sectionEmoji || ''} ${sectionTitle}`.trim() : null

      if (sectionKey && sectionKey !== currentSection) {
        sections.push({
          type: 'section',
          key: sectionKey,
          label: sectionKey
        })
        currentSection = sectionKey
      } else if (!sectionTitle && currentSection !== null) {
        currentSection = null
      }

      sections.push({
        type: 'article',
        key: article.url,
        article,
        index
      })
    })

    return sections
  }, [sortedArticles])

  return (
    <div className="article-list">
      {sectionsWithArticles.map((item) => (
        item.type === 'section' ? (
          <div key={item.key} className="section-title">
            {item.label}
          </div>
        ) : (
          <ArticleCard
            key={item.key}
            article={item.article}
            index={item.index}
            onCopySummary={onCopySummary}
          />
        )
      ))}
    </div>
  )
}

export default ArticleList
