// client/src/components/CacheToggle.vue
<script setup>
import { useCacheSettings } from '@/composables/useCacheSettings'

const { enabled, statusText } = useCacheSettings()
</script>

<template>
  <div class="cache-toggle-container" data-testid="cache-toggle-container">
    <label class="cache-toggle-label" for="cacheToggle">
      <input
        id="cacheToggle"
        v-model="enabled"
        type="checkbox"
        class="cache-toggle-input"
        data-testid="cache-toggle-input"
        aria-label="Enable cache"
      >
      <span class="cache-toggle-checkbox" data-testid="cache-toggle-switch" />
      <span class="cache-toggle-text">Cache</span>
      <span class="cache-toggle-status" data-testid="cache-toggle-status">{{ statusText }}</span>
    </label>
  </div>
</template>

<style scoped>
.cache-toggle-container {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 12px;
  margin-bottom: 20px;
  background: var(--bg);
  border-radius: 8px;
  border: 1px solid var(--border);
}

.cache-toggle-label {
  display: flex;
  align-items: center;
  gap: 10px;
  cursor: pointer;
  font-size: 15px;
  color: var(--text);
  user-select: none;
}

.cache-toggle-checkbox {
  position: relative;
  width: 48px;
  height: 26px;
  background: #cbd5e1;
  border-radius: 13px;
  transition: background-color 0.2s ease;
  cursor: pointer;
  border: 2px solid transparent;
}

.cache-toggle-checkbox::after {
  content: '';
  position: absolute;
  top: 2px;
  left: 2px;
  width: 18px;
  height: 18px;
  background: white;
  border-radius: 50%;
  transition: transform 0.2s ease;
  box-shadow: 0 2px 4px rgba(0,0,0,0.2);
}

.cache-toggle-input {
  position: absolute;
  opacity: 0;
  width: 0;
  height: 0;
}

.cache-toggle-input:checked + .cache-toggle-checkbox {
  background: #22c55e;
}

.cache-toggle-input:checked + .cache-toggle-checkbox::after {
  transform: translateX(22px);
}

.cache-toggle-input:focus-visible + .cache-toggle-checkbox {
  outline: 3px solid rgba(26,115,232,0.45);
  outline-offset: 2px;
}

.cache-toggle-text {
  font-weight: 500;
}

.cache-toggle-status {
  font-size: 13px;
  color: var(--muted);
  margin-left: 4px;
}
</style>

// client/src/components/CacheToggle.jsx
import { useSupabaseStorage } from '../hooks/useSupabaseStorage'

function CacheToggle() {
  const [enabled, setEnabled, , { loading }] = useSupabaseStorage('cache:enabled', true)

  return (
    <div className="flex items-center">
      <label className="flex items-center gap-2.5 cursor-pointer select-none group" htmlFor="cacheToggle">
        <span className={`text-xs font-bold uppercase tracking-wider transition-colors ${enabled ? 'text-brand-600' : 'text-slate-400 group-hover:text-slate-500'}`}>
          Cache
        </span>
        <div className="relative">
          <input
            id="cacheToggle"
            type="checkbox"
            className="sr-only"
            checked={enabled}
            disabled={loading}
            onChange={(e) => setEnabled(e.target.checked)}
          />
          <div className={`w-10 h-6 rounded-full transition-colors duration-200 ease-[cubic-bezier(0.4,0,0.2,1)] ${enabled ? 'bg-brand-600' : 'bg-slate-200'}`}></div>
          <div className={`absolute top-1 left-1 bg-white w-4 h-4 rounded-full shadow-sm transition-transform duration-200 ease-[cubic-bezier(0.4,0,0.2,1)] ${enabled ? 'translate-x-4' : 'translate-x-0'}`}></div>
        </div>
      </label>
    </div>
  )
}

export default CacheToggle
