// temp_mock_design/client/src/components/ResultsDisplay.jsx
import { useSupabaseStorage } from "../hooks/useSupabaseStorage";
import { getNewsletterScrapeKey } from "../lib/storageKeys";
import ArticleList from "./ArticleList";

// import './ResultsDisplay.css' - Removed

function ResultsDisplay({ results }) {
	const statsLines = [
		`${results.stats.total_articles} Articles`,
		`${results.stats.unique_urls} Sources`,
		results.source === "local cache" ? "Cached" : "Live",
	];

	const debugLogs = results.debugLogs || [];

	return (
		<div className="animate-slide-up pb-20">
			{/* Stats Pills */}
			<div className="flex flex-wrap gap-2 mb-8 justify-center">
				{statsLines.map((line, index) => (
					<span
						className="px-3 py-1 bg-slate-100 text-slate-500 rounded-full text-[10px] font-bold uppercase tracking-wider border border-slate-200/60"
						key={index}
					>
						{line}
					</span>
				))}
			</div>

			{debugLogs.length > 0 && (
				<div className="mb-8 text-center">
					<details className="group inline-block">
						<summary className="list-none cursor-pointer text-[10px] font-bold text-slate-300 uppercase tracking-widest hover:text-brand-500 transition-colors">
							View Debug Logs
						</summary>
						<div className="mt-4 text-left">
							<pre className="p-4 bg-slate-900 text-slate-400 rounded-xl text-[10px] overflow-x-auto font-mono shadow-inner max-h-60 scrollbar-thin">
								{debugLogs.join("\n")}
							</pre>
						</div>
					</details>
				</div>
			)}

			<div className="space-y-16">
				{(results.payloads || []).map((payload) => (
					<DailyResults key={payload.date} payload={payload} />
				))}
			</div>
		</div>
	);
}

function DailyResults({ payload }) {
	const [livePayload, , , { loading }] = useSupabaseStorage(getNewsletterScrapeKey(payload.date), payload);

	const date = livePayload?.date ?? payload.date;
	const articles = (livePayload?.articles ?? payload.articles).map((article, index) => ({
		...article,
		originalOrder: index,
	}));
	const issues = livePayload?.issues ?? payload.issues ?? [];

	// Format date nicely
	const dateObj = new Date(date);
	const formattedDate = dateObj.toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" });

	return (
		<section className="relative">
			{/* Sticky Date Header */}
			<div className="sticky top-24 z-30 flex justify-center mb-8 pointer-events-none">
				<div className="bg-slate-900/90 backdrop-blur-md text-white pl-5 pr-5 py-2 rounded-full shadow-soft-hover pointer-events-auto ring-1 ring-white/20">
					<h2 className="text-sm font-bold font-display tracking-wide flex items-center gap-2">
						{formattedDate}
						{loading && <i className="w-3 h-3 animate-spin opacity-70" data-lucide="loader-2"></i>}
					</h2>
				</div>
			</div>

			<div className="bg-white/40 backdrop-blur-sm rounded-[2rem] p-2 sm:p-6 border border-slate-100/60 shadow-sm">
				{issues.map((issue) => (
					<div className="mb-10 last:mb-0" key={`${date}-${issue.category}`}>
						{/* Issue Category Header */}
						<div className="flex items-center gap-4 mb-6 pl-2 mt-2">
							<div className="h-px flex-1 bg-slate-200/60"></div>
							<h4 className="font-display font-bold text-xl text-slate-800 tracking-tight">{issue.category}</h4>
							<div className="h-px flex-1 bg-slate-200/60"></div>
						</div>

						{(issue.title || issue.subtitle) && (
							<div className="text-center mb-8 px-4 max-w-lg mx-auto">
								{issue.title && (
									<p className="text-base font-medium text-slate-700 italic font-serif">"{issue.title}"</p>
								)}
								{issue.subtitle && issue.subtitle !== issue.title && (
									<p className="text-xs text-slate-400 mt-2 font-medium uppercase tracking-wide">{issue.subtitle}</p>
								)}
							</div>
						)}

						<ArticleList articles={articles.filter((article) => article.category === issue.category)} />
					</div>
				))}

				{articles.some((article) => !article.category) && (
					<ArticleList articles={articles.filter((article) => !article.category)} />
				)}
			</div>
		</section>
	);
}

export default ResultsDisplay;

// client/src/components/ResultsDisplay.vue
<script setup>
import { computed, ref } from 'vue'
import ArticleList from './ArticleList.vue'

const props = defineProps({
  results: {
    type: Object,
    required: true
  }
})

const showToast = ref(false)
let toastTimeout = null

// Build stats display
const statsLines = computed(() => {
  const stats = props.results.stats
  const lines = [
    `📊 Stats: ${stats.total_articles} articles, ${stats.unique_urls} unique URLs`,
    `📅 Dates: ${stats.dates_with_content}/${stats.dates_processed} with content`
  ]

  if (props.results.source) {
    lines.push(`Source: ${props.results.source}`)
  }

  return lines
})

// Group articles by date
const articlesByDate = computed(() => {
  const payloads = props.results.payloads || []
  return payloads.map(payload => ({
    date: payload.date,
    articles: payload.articles.map((article, index) => ({
      ...article,
      originalOrder: index
    })),
    issues: payload.issues || []
  }))
})

// Debug logs (if any)
const debugLogs = computed(() => props.results.debugLogs || [])

function handleCopySummary() {
  clearTimeout(toastTimeout)
  showToast.value = true
  toastTimeout = setTimeout(() => {
    showToast.value = false
  }, 2000)
}
</script>

<template>
  <div id="result" class="result success">
    <!-- Stats display -->
    <div class="stats">
      <div v-for="(line, index) in statsLines" :key="index">
        {{ line }}
      </div>
    </div>

    <!-- Debug logs (collapsible) -->
    <div v-if="debugLogs.length > 0" id="logs-slot" class="logs-slot">
      <details>
        <summary>Debug logs</summary>
        <pre>{{ debugLogs.join('\n') }}</pre>
      </details>
    </div>

    <!-- Articles grouped by date -->
    <main id="write">
      <div
        v-for="dateGroup in articlesByDate"
        :key="dateGroup.date"
        class="date-group"
      >
        <!-- Date header -->
        <div class="date-header-container" :data-date="dateGroup.date">
          <h2>{{ dateGroup.date }}</h2>
        </div>

        <!-- Issues/Categories -->
        <div
          v-for="issue in dateGroup.issues"
          :key="`${dateGroup.date}-${issue.category}`"
          class="issue-section"
        >
          <div class="issue-header-container">
            <h4>{{ issue.category }}</h4>
          </div>

          <!-- Issue title block (if present) -->
          <div v-if="issue.title || issue.subtitle" class="issue-title-block">
            <div v-if="issue.title" class="issue-title-line">
              {{ issue.title }}
            </div>
            <div v-if="issue.subtitle && issue.subtitle !== issue.title" class="issue-title-line">
              {{ issue.subtitle }}
            </div>
          </div>

          <!-- Articles for this issue/category -->
          <ArticleList
            :articles="dateGroup.articles.filter(a => a.category === issue.category)"
            @copy-summary="handleCopySummary"
          />
        </div>

        <!-- Articles without a category -->
        <ArticleList
          v-if="dateGroup.articles.some(a => !a.category)"
          :articles="dateGroup.articles.filter(a => !a.category)"
          @copy-summary="handleCopySummary"
        />
      </div>
    </main>

    <!-- Copy toast notification -->
    <Teleport to="body">
      <div
        id="copyToast"
        :class="{ show: showToast }"
        class="copy-toast"
      >
        Copied to clipboard
      </div>
    </Teleport>
  </div>
</template>

<style scoped>
.result {
  margin-top: 20px;
  padding: 0;
  background-color: transparent;
  border-radius: 0;
  display: block;
  border: none;
}

.stats {
  background-color: #fff3cd;
  border: 1px solid #ffeaa7;
  color: #856404;
  margin-bottom: 15px;
  padding: 10px;
  border-radius: 4px;
}

.logs-slot {
  margin-bottom: 15px;
}

.logs-slot details {
  background: #f6f7f9;
  padding: 10px;
  border-radius: 4px;
  border: 1px solid #e5e7eb;
}

.logs-slot summary {
  cursor: pointer;
  font-weight: 600;
  color: #475569;
  user-select: none;
}

.logs-slot pre {
  margin-top: 10px;
  font-size: 13px;
  line-height: 1.5;
  white-space: pre-wrap;
  word-wrap: break-word;
  color: #0f172a;
}

/* Date headers */
.date-header-container {
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 100%;
  margin: 0;
}

.date-header-container h2 {
  text-align: center;
  width: 100%;
  font-weight: normal;
  color: var(--text, #0f172a);
  margin-top: 2em;
}

.date-header-container h2::after {
  border-bottom: 1px solid #2f2f2f;
  content: '';
  width: 100px;
  display: block;
  margin: 0.4em auto 0;
  height: 1px;
}

/* Issue headers */
.issue-header-container h4 {
  text-align: left;
  margin: 1.5em 0 0.5em;
  font-style: normal;
  color: var(--text, #0f172a);
}

.issue-title-block {
  margin: 12px 0 18px;
  text-align: center;
  font-style: italic;
  color: #9ca3af;
  font-size: 0.95em;
  line-height: 1.6;
}

.issue-title-block .issue-title-line + .issue-title-line {
  margin-top: 4px;
}

/* Copy toast */
.copy-toast {
  position: fixed;
  left: 50%;
  bottom: 32px;
  transform: translateX(-50%) translateY(20px);
  background: rgba(255, 255, 255, 0.95);
  backdrop-filter: blur(10px);
  color: var(--text, #0f172a);
  padding: 10px 18px;
  border-radius: 999px;
  font-size: 14px;
  font-weight: 500;
  opacity: 0;
  pointer-events: none;
  transition: opacity 0.25s ease, transform 0.25s ease;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08), 0 2px 4px rgba(0, 0, 0, 0.06);
  border: 1px solid rgba(0, 0, 0, 0.06);
  z-index: 999;
}

.copy-toast.show {
  opacity: 1;
  transform: translateX(-50%) translateY(0);
}
</style>
