// temp_mock_design/client/src/components/ScrapeForm.jsx
import { useActionState, useEffect, useState } from "react";
import { useSupabaseStorage } from "../hooks/useSupabaseStorage";
import { scrapeNewsletters } from "../lib/scraper";

// import './ScrapeForm.css' - Removed

function ScrapeForm({ onResults }) {
	const [startDate, setStartDate] = useState("");
	const [endDate, setEndDate] = useState("");
	const [cacheEnabled] = useSupabaseStorage("cache:enabled", true);
	const [progress, setProgress] = useState(0);

	useEffect(() => {
		const today = new Date();
		const threeDaysAgo = new Date(today);
		threeDaysAgo.setDate(today.getDate() - 3);
		setEndDate(today.toISOString().split("T")[0]);
		setStartDate(threeDaysAgo.toISOString().split("T")[0]);
	}, []);

	const [state, formAction, isPending] = useActionState(
		async (previousState, formData) => {
			const start = formData.get("start_date");
			const end = formData.get("end_date");

			const startDateObj = new Date(start);
			const endDateObj = new Date(end);
			const daysDiff = Math.ceil((endDateObj - startDateObj) / (1000 * 60 * 60 * 24));

			if (startDateObj > endDateObj) {
				return { error: "Start date must be before or equal to end date." };
			}
			if (daysDiff >= 31) {
				return { error: "Date range cannot exceed 31 days." };
			}

			setProgress(50);

			try {
				const results = await scrapeNewsletters(start, end, cacheEnabled);
				setProgress(100);
				onResults(results);
				return { success: true };
			} catch (err) {
				setProgress(0);
				return { error: err.message || "Network error" };
			}
		},
		{ success: false },
	);

	return (
		<div className="w-full">
			<h2 className="text-lg font-display font-bold text-slate-800 mb-5 flex items-center gap-2">
				<div className="bg-brand-50 p-1.5 rounded-lg">
					<i className="w-4 h-4 text-brand-600" data-lucide="calendar-range"></i>
				</div>
				Select Range
			</h2>

			<form action={formAction} className="space-y-5" id="scrapeForm">
				<div className="grid grid-cols-2 gap-4">
					<div className="space-y-2">
						<label
							className="block text-[10px] font-bold text-slate-400 uppercase tracking-widest"
							htmlFor="start_date"
						>
							From
						</label>
						<input
							className="w-full px-4 py-3 bg-slate-50/50 border border-slate-200 rounded-xl text-slate-700 text-sm font-medium focus:outline-none focus:ring-2 focus:ring-brand-500/10 focus:border-brand-500 transition-all"
							id="start_date"
							name="start_date"
							onChange={(e) => setStartDate(e.target.value)}
							required
							type="date"
							value={startDate}
						/>
					</div>

					<div className="space-y-2">
						<label className="block text-[10px] font-bold text-slate-400 uppercase tracking-widest" htmlFor="end_date">
							To
						</label>
						<input
							className="w-full px-4 py-3 bg-slate-50/50 border border-slate-200 rounded-xl text-slate-700 text-sm font-medium focus:outline-none focus:ring-2 focus:ring-brand-500/10 focus:border-brand-500 transition-all"
							id="end_date"
							name="end_date"
							onChange={(e) => setEndDate(e.target.value)}
							required
							type="date"
							value={endDate}
						/>
					</div>
				</div>

				<button
					className="w-full mt-2 px-6 py-3.5 rounded-xl bg-slate-900 text-white font-bold tracking-wide hover:bg-brand-600 hover:shadow-lg hover:shadow-brand-500/20 active:scale-[0.98] disabled:opacity-70 disabled:cursor-not-allowed transition-all duration-200 flex items-center justify-center gap-2.5"
					disabled={isPending}
					id="scrapeBtn"
					type="submit"
				>
					{isPending ? (
						<>
							<i className="w-4 h-4 animate-spin" data-lucide="loader-2"></i>
							<span>Scraping...</span>
						</>
					) : (
						<>
							<i className="w-4 h-4" data-lucide="search"></i>
							<span>Fetch Articles</span>
						</>
					)}
				</button>
			</form>

			{isPending && (
				<div className="mt-5">
					<div className="h-1 w-full bg-slate-100 rounded-full overflow-hidden">
						<div
							className="h-full bg-brand-500 transition-all duration-700 ease-out rounded-full"
							style={{ width: `${progress}%` }}
						/>
					</div>
					<p className="text-center text-[10px] text-slate-400 mt-2 font-bold uppercase tracking-widest">
						Retrieving Content
					</p>
				</div>
			)}

			{state.error && (
				<div className="mt-5 p-4 bg-red-50 border border-red-100 text-red-600 text-sm rounded-xl flex items-start gap-3 animate-fade-in">
					<i className="w-5 h-5 mt-0.5 flex-shrink-0" data-lucide="alert-circle"></i>
					<span className="font-medium">{state.error}</span>
				</div>
			)}
		</div>
	);
}

export default ScrapeForm;

// client/src/components/ScrapeForm.vue
<script setup>
import { ref, computed, onMounted } from 'vue'
import { useScraper } from '@/composables/useScraper'

const emit = defineEmits(['results'])

const startDate = ref('')
const endDate = ref('')

const { scrape, loading, error, progress } = useScraper()

// Computed validation
const daysDiff = computed(() => {
  if (!startDate.value || !endDate.value) return 0
  const start = new Date(startDate.value)
  const end = new Date(endDate.value)
  return Math.ceil((end - start) / (1000 * 60 * 60 * 24))
})

const validationError = computed(() => {
  if (!startDate.value || !endDate.value) return null

  const start = new Date(startDate.value)
  const end = new Date(endDate.value)

  if (start > end) {
    return 'Start date must be before or equal to end date.'
  }
  if (daysDiff.value >= 31) {
    return 'Date range cannot exceed 31 days. Please select a smaller range.'
  }
  return null
})

const isDisabled = computed(() => loading.value || !!validationError.value)

// Set default dates on mount
onMounted(() => {
  setDefaultDates()
})

function setDefaultDates() {
  const today = new Date()
  const threeDaysAgo = new Date(today)
  threeDaysAgo.setDate(today.getDate() - 3)

  endDate.value = today.toISOString().split('T')[0]
  startDate.value = threeDaysAgo.toISOString().split('T')[0]
}

async function handleSubmit() {
  if (validationError.value) return

  const results = await scrape(startDate.value, endDate.value)
  if (results) {
    emit('results', results)
  }
}
</script>

<template>
  <div>
    <form id="scrapeForm" @submit.prevent="handleSubmit">
      <div class="form-group">
        <label for="start_date">Start Date:</label>
        <input
          id="start_date"
          v-model="startDate"
          type="date"
          name="start_date"
          required
        >
      </div>

      <div class="form-group">
        <label for="end_date">End Date:</label>
        <input
          id="end_date"
          v-model="endDate"
          type="date"
          name="end_date"
          required
        >
      </div>

      <button
        id="scrapeBtn"
        type="submit"
        :disabled="isDisabled"
        data-testid="scrape-btn"
      >
        {{ loading ? 'Scraping...' : 'Scrape Newsletters' }}
      </button>
    </form>

    <!-- Progress bar -->
    <div v-if="loading" class="progress">
      <div id="progress-text">
        Scraping newsletters... This may take several minutes.
      </div>
      <div class="progress-bar">
        <div
          class="progress-fill"
          :style="{ width: `${progress}%` }"
        />
      </div>
    </div>

    <!-- Validation error -->
    <div v-if="validationError" class="error" role="alert">
      {{ validationError }}
    </div>

    <!-- Network error -->
    <div v-if="error" class="error" role="alert">
      Error: {{ error }}
    </div>
  </div>
</template>

<style scoped>
.form-group {
  margin-bottom: 20px;
  display: inline-block;
  width: 45%;
  margin-right: 5%;
}

.form-group:last-child {
  margin-right: 0;
}

label {
  display: block;
  margin-bottom: 5px;
  font-weight: bold;
  color: var(--muted);
}

input[type="date"] {
  width: 100%;
  padding: 10px 12px;
  border: 1px solid var(--border);
  border-radius: 8px;
  font-size: 16px;
  box-sizing: border-box;
  background: var(--surface);
  color: var(--text);
  min-height: 44px;
}

button {
  background-color: #007bff;
  color: white;
  padding: 12px 24px;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  font-size: 16px;
  width: 100%;
  margin-top: 20px;
  min-height: 44px;
}

button:hover {
  background-color: #0056b3;
}

button:disabled {
  background-color: #ccc;
  cursor: not-allowed;
}

.progress {
  display: block;
  margin: 20px 0;
  padding: 15px;
  background-color: #e3f2fd;
  border-radius: 4px;
  border-left: 4px solid #2196f3;
}

.progress-bar {
  width: 100%;
  height: 20px;
  background-color: #ddd;
  border-radius: 10px;
  overflow: hidden;
  margin-top: 10px;
}

.progress-fill {
  height: 100%;
  background-color: #2196f3;
  transition: width 0.3s ease;
}

.error {
  background-color: #f8d7da;
  border: 1px solid #f5c6cb;
  color: #721c24;
  padding: 10px 12px;
  border-radius: 6px;
  margin-top: 10px;
}

@media (max-width: 480px) {
  .form-group {
    width: 100%;
    margin-right: 0;
  }
}
</style>
